language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  - pip
install:
  - pip install -r example/requirements.txt
  - pip install flake8
  - pip install pytest
  - make install
script:
  - py.test -s
